/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Models.Customer;
import Models.CustomerCard;
import Models.CustomerCardList;
import Models.History;
import Ultility.Cautions;
import Ultility.IDGenerator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chi Cute
 */
public class CardTest extends javax.swing.JFrame {

    /**
     * Creates new form CardTest
     */
    public CardTest() {
        initComponents();
        customerModel = (DefaultTableModel) customerTable.getModel();
        System.out.println(cardList.getList().size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CustomerInforPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        memberCardIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberAddressTextPane = new javax.swing.JTextPane();
        DeleteCardButton = new javax.swing.JButton();
        UpdateCustomerDateButton = new javax.swing.JButton();
        CardInforPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        memberTotalPayTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        memberUsagePointTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        memberUsedPointTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        memberCardRankTextField = new javax.swing.JTextField();
        needMore = new javax.swing.JLabel();
        toNextRank = new javax.swing.JLabel();
        morePayToNextRank = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        memberFirstNameTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        memberLastNameTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        memberAgeTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        memberPhoneNumberTextField = new javax.swing.JTextField();
        memberGenderComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ToolsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        ShowCardListButton = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        CustomerCardTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        AddMemberPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        newMemberFirstNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        newMemberLastNameTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        newMemberAgeTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        newMemberPhoneNumberTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        newMemberAddressTextPane = new javax.swing.JTextPane();
        CreateNewCardButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newMemberGenderComboBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(970, 560));
        jPanel1.setLayout(new java.awt.BorderLayout());

        CustomerInforPanel.setBackground(new java.awt.Color(255, 255, 255));
        CustomerInforPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setText("Mã khách/Mã thẻ:");

        memberCardIDTextField.setEditable(false);
        memberCardIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberCardIDTextField.setFocusable(false);

        jLabel6.setText("Địa chỉ:");

        memberAddressTextPane.setPreferredSize(new java.awt.Dimension(62, 48));
        jScrollPane1.setViewportView(memberAddressTextPane);

        DeleteCardButton.setBackground(new java.awt.Color(255, 51, 0));
        DeleteCardButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteCardButton.setText("XÓA THẺ");
        DeleteCardButton.setFocusable(false);
        DeleteCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCardButtonActionPerformed(evt);
            }
        });

        UpdateCustomerDateButton.setBackground(new java.awt.Color(153, 255, 0));
        UpdateCustomerDateButton.setText("CẬP NHẬT");
        UpdateCustomerDateButton.setFocusable(false);
        UpdateCustomerDateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateCustomerDateButtonMouseClicked(evt);
            }
        });
        UpdateCustomerDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerDateButtonActionPerformed(evt);
            }
        });

        CardInforPanel.setBackground(new java.awt.Color(255, 255, 255));
        CardInforPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thẻ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel7.setText("Điểm khả dụng:");

        memberTotalPayTextField.setEditable(false);
        memberTotalPayTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberTotalPayTextField.setFocusable(false);
        memberTotalPayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberTotalPayTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Điểm đã quy đổi:");

        memberUsagePointTextField.setEditable(false);
        memberUsagePointTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberUsagePointTextField.setFocusable(false);
        memberUsagePointTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUsagePointTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Tổng chi tiêu:");

        memberUsedPointTextField.setEditable(false);
        memberUsedPointTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberUsedPointTextField.setFocusable(false);
        memberUsedPointTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUsedPointTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Thứ hạng thẻ:");

        memberCardRankTextField.setEditable(false);
        memberCardRankTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memberCardRankTextField.setFocusable(false);
        memberCardRankTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberCardRankTextFieldActionPerformed(evt);
            }
        });

        needMore.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        needMore.setForeground(new java.awt.Color(153, 153, 153));
        needMore.setText("Chi tiêu thêm");

        toNextRank.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        toNextRank.setForeground(new java.awt.Color(153, 153, 153));
        toNextRank.setText("để lên thứ hạng tiếp theo");

        morePayToNextRank.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        morePayToNextRank.setForeground(new java.awt.Color(153, 153, 153));
        morePayToNextRank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        morePayToNextRank.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout CardInforPanelLayout = new javax.swing.GroupLayout(CardInforPanel);
        CardInforPanel.setLayout(CardInforPanelLayout);
        CardInforPanelLayout.setHorizontalGroup(
            CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardInforPanelLayout.createSequentialGroup()
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardInforPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(memberUsedPointTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(memberTotalPayTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberCardRankTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberUsagePointTextField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CardInforPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(needMore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(morePayToNextRank, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toNextRank)))
                .addContainerGap())
        );
        CardInforPanelLayout.setVerticalGroup(
            CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardInforPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(memberUsagePointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(memberUsedPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(memberTotalPayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(memberCardRankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(needMore)
                        .addComponent(toNextRank))
                    .addComponent(morePayToNextRank, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel36.setText("Họ:");

        memberFirstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel37.setText("Tên:");

        memberLastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel38.setText("Tuổi:");

        memberAgeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel39.setText("SĐT:");

        memberPhoneNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        memberGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        jLabel3.setText("Giới tính:");

        javax.swing.GroupLayout CustomerInforPanelLayout = new javax.swing.GroupLayout(CustomerInforPanel);
        CustomerInforPanel.setLayout(CustomerInforPanelLayout);
        CustomerInforPanelLayout.setHorizontalGroup(
            CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardInforPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerInforPanelLayout.createSequentialGroup()
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel36))
                                .addGap(12, 12, 12)
                                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                                        .addComponent(memberAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(memberGenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                                        .addComponent(memberPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                                        .addComponent(memberFirstNameTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(memberLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(memberCardIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(DeleteCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateCustomerDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        CustomerInforPanelLayout.setVerticalGroup(
            CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerInforPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberCardIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(memberFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(memberLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(memberGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(memberAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(memberPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(CustomerInforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateCustomerDateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteCardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CardInforPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(CustomerInforPanel, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        ToolsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ToolsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("ID/Tên khách hàng:");
        ToolsPanel.add(jLabel4);

        SearchTextField.setPreferredSize(new java.awt.Dimension(200, 26));
        ToolsPanel.add(SearchTextField);

        SearchButton.setBackground(new java.awt.Color(153, 255, 255));
        SearchButton.setText("Tìm kiếm");
        SearchButton.setFocusable(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        ToolsPanel.add(SearchButton);

        ShowCardListButton.setBackground(new java.awt.Color(153, 255, 255));
        ShowCardListButton.setText("Hiển thị toàn bộ danh sách");
        ShowCardListButton.setFocusable(false);
        ShowCardListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCardListButtonActionPerformed(evt);
            }
        });
        ToolsPanel.add(ShowCardListButton);

        jPanel6.add(ToolsPanel, java.awt.BorderLayout.PAGE_START);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(652, 557));

        CustomerCardTable.setBackground(new java.awt.Color(255, 255, 255));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách/Mã thẻ", "Họ", "Tên", "Tuổi", "Giới tính", "SĐT", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        customerTable.setColumnSelectionAllowed(true);
        customerTable.setFocusable(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(customerTable);

        javax.swing.GroupLayout CustomerCardTableLayout = new javax.swing.GroupLayout(CustomerCardTable);
        CustomerCardTable.setLayout(CustomerCardTableLayout);
        CustomerCardTableLayout.setHorizontalGroup(
            CustomerCardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerCardTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );
        CustomerCardTableLayout.setVerticalGroup(
            CustomerCardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        AddMemberPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddMemberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm thành viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel11.setText("Họ:");

        newMemberFirstNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("Tên:");

        newMemberLastNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Tuổi:");

        newMemberAgeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setText("SĐT:");

        newMemberPhoneNumberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setText("Địa chỉ:");

        newMemberAddressTextPane.setPreferredSize(new java.awt.Dimension(62, 48));
        jScrollPane3.setViewportView(newMemberAddressTextPane);

        CreateNewCardButton.setBackground(new java.awt.Color(153, 255, 255));
        CreateNewCardButton.setText("TẠO THẺ & THÊM THÀNH VIÊN");
        CreateNewCardButton.setFocusable(false);
        CreateNewCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewCardButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Giới tính:");

        newMemberGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ ", "Khác" }));

        javax.swing.GroupLayout AddMemberPanelLayout = new javax.swing.GroupLayout(AddMemberPanel);
        AddMemberPanel.setLayout(AddMemberPanelLayout);
        AddMemberPanelLayout.setHorizontalGroup(
            AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMemberPanelLayout.createSequentialGroup()
                .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMemberPanelLayout.createSequentialGroup()
                        .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMemberPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(AddMemberPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddMemberPanelLayout.createSequentialGroup()
                                .addComponent(newMemberAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newMemberGenderComboBox, 0, 123, Short.MAX_VALUE))
                            .addGroup(AddMemberPanelLayout.createSequentialGroup()
                                .addComponent(newMemberFirstNameTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newMemberLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddMemberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newMemberPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AddMemberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMemberPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateNewCardButton)
                .addGap(37, 37, 37))
        );
        AddMemberPanelLayout.setVerticalGroup(
            AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMemberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(newMemberFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(newMemberLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(newMemberAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(newMemberGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newMemberPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMemberPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateNewCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cài đặt chính sách", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setText("Chi tiêu");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 102, 0));
        jLabel18.setText("Đồng");

        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Bạc");

        jLabel21.setForeground(new java.awt.Color(255, 204, 0));
        jLabel21.setText("Vàng");

        jLabel22.setForeground(new java.awt.Color(0, 204, 255));
        jLabel22.setText("Kim");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel23.setForeground(new java.awt.Color(0, 204, 255));
        jLabel23.setText("cương");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("70M");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("30M");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("10M");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel27.setText("Thứ hạng");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("0");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Giảm 2% hóa đơn từ 1.890.000");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Giảm 3% hóa đơn từ 2.490.000");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Ưu đãi hạng đồng");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Ưu đãi hạng bạc");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Giảm 5% hóa đơn từ 4.490.000");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Giảm 7% hóa đơn từ 6.990.000");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Ưu đãi hạng vàng");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel33))
                                .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41))
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35)
                                        .addGap(77, 77, 77))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)))
                                .addComponent(jLabel28))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel31)))))
                    .addComponent(jSeparator1)))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CustomerCardTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(AddMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerCardTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.add(MainPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCardButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(CustomerCardPanel.this,
                "Vui lòng chọn 1 hàng!");
            return;
        } else {
            int response = JOptionPane.showConfirmDialog(CustomerCardPanel.this,
                "Bạn muốn xóa thẻ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                customerModel.removeRow(selectedRow);
                customerCardList.getList().remove(selectedRow);
                resetMemberCardValue();
            } else {
                return;
            }
        }
    }//GEN-LAST:event_DeleteCardButtonActionPerformed

    private void UpdateCustomerDateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCustomerDateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateCustomerDateButtonMouseClicked

    private void UpdateCustomerDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerDateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(CustomerCardPanel.this,
                "Vui lòng chọn 1 hàng!");
        } else {
            String firstName = memberFirstNameTextField.getText();
            String lastName = memberLastNameTextField.getText();
            String ageStr = memberAgeTextField.getText();
            String genderStr = memberGenderComboBox.getSelectedItem().toString();
            Gender genderEnum = castStringToGender(genderStr);
            String phoneNo = memberPhoneNumberTextField.getText();
            String address = memberAddressTextPane.getText();

            int age = Integer.parseInt(ageStr);
            if (firstName.equalsIgnoreCase(customerCardList.getList().get(selectedRow).getCustomer().getFirstName())
                && lastName.equalsIgnoreCase(customerCardList.getList().get(selectedRow).getCustomer().getLastName())
                && age == customerCardList.getList().get(selectedRow).getCustomer().getAge()
                && genderEnum.equals(customerCardList.getList().get(selectedRow).getCustomer().getGender())
                && phoneNo.equals(customerCardList.getList().get(selectedRow).getCustomer().getPhoneNumber())
                && address.equals(customerCardList.getList().get(selectedRow).getCustomer().getAddress())) {
                JOptionPane.showMessageDialog(CustomerCardPanel.this,
                    "Bạn chưa thay đổi bất kì thông tin nào!");
                return;
            }
            if (checkInformation(firstName, lastName, ageStr, phoneNo, address)) {
                String phone = customerCardList.getList().get(selectedRow).getCustomer().getPhoneNumber();
                customerCardList.getList().get(selectedRow).getCustomer().setPhoneNumber("0000000000");
                if (existedPhoneNumber(phoneNo)) {
                    JOptionPane.showMessageDialog(CustomerCardPanel.this,
                        "Số điện thoại đã được đăng kí!");
                    customerCardList.getList().get(selectedRow).getCustomer().setPhoneNumber(phone);
                    memberPhoneNumberTextField.setText("");
                    return;
                }
                int response = JOptionPane.showConfirmDialog(CustomerCardPanel.this,
                    "Bạn muốn thay đổi thông tin khách hàng?",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION);

                if (response == JOptionPane.YES_OPTION) {
                    customerCardList.getList().get(selectedRow).getCustomer().setFirstName(firstName);
                    customerCardList.getList().get(selectedRow).getCustomer().setLastName(lastName);
                    customerCardList.getList().get(selectedRow).getCustomer().setAge(age);
                    customerCardList.getList().get(selectedRow).getCustomer().setGender(genderEnum);
                    customerCardList.getList().get(selectedRow).getCustomer().setPhoneNumber(phoneNo);
                    customerCardList.getList().get(selectedRow).getCustomer().setAddress(address);
                    addAllCustomerCardToTable();
                    resetMemberCardValue();
                }

            }
        }
    }//GEN-LAST:event_UpdateCustomerDateButtonActionPerformed

    private void memberTotalPayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberTotalPayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberTotalPayTextFieldActionPerformed

    private void memberUsagePointTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUsagePointTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberUsagePointTextFieldActionPerformed

    private void memberUsedPointTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUsedPointTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberUsedPointTextFieldActionPerformed

    private void memberCardRankTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberCardRankTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberCardRankTextFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed

        String searchingKey = SearchTextField.getText().toLowerCase();
        boolean found = false;
        if (searchingKey.isBlank()) {
            return;
        } else {
            if (customerCardList.getList().isEmpty()) {
                JOptionPane.showMessageDialog(CustomerCardPanel.this,
                    "Danh sách trống!");
            } else {
                clearTableModel(customerModel);
                for (int i = 0; i < customerCardList.getList().size(); i++) {
                    if (customerCardList.getList().get(i).getID().equals(searchingKey)
                        || customerCardList.getList().get(i).getCustomer().getFirstName().toLowerCase().contains(searchingKey)
                        || customerCardList.getList().get(i).getCustomer().getLastName().toLowerCase().contains(searchingKey)) {
                        CustomerCard card = customerCardList.getList().get(i);
                        addNewCustomerCardToTable(card);
                        found = true;
                    }
                }
                if (!found) {
                    JOptionPane.showMessageDialog(CustomerCardPanel.this,
                        "Không tìm thấy!");
                    SearchTextField.setText("");
                }
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ShowCardListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCardListButtonActionPerformed
        // TODO add your handling code here:
        SearchTextField.setText("");
        if (customerCardList.getList().isEmpty()) {
            JOptionPane.showMessageDialog(CustomerCardPanel.this,
                "Danh sách trống!");
        } else {
            clearTableModel(customerModel);
            addAllCustomerCardToTable();
        }
    }//GEN-LAST:event_ShowCardListButtonActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        int rowIndex = customerTable.getSelectedRow();

        memberCardIDTextField.setText(customerModel.getValueAt(rowIndex, 0).toString());
        memberFirstNameTextField.setText(customerModel.getValueAt(rowIndex, 1).toString());
        memberLastNameTextField.setText(customerModel.getValueAt(rowIndex, 2).toString());
        memberAgeTextField.setText(customerModel.getValueAt(rowIndex, 3).toString());
        memberGenderComboBox.setSelectedItem(customerModel.getValueAt(rowIndex, 4).toString());
        memberPhoneNumberTextField.setText(customerModel.getValueAt(rowIndex, 5).toString());
        memberAddressTextPane.setText(customerModel.getValueAt(rowIndex, 6).toString());

        CustomerCard cc = customerCardList.getList().get(rowIndex);
        BigInteger usedPoint = BigInteger.valueOf(0);
        BigInteger pay = BigInteger.valueOf(0);
        BigInteger usagePoint = cc.getPoint().subtract(usedPoint);
        String rank = cardRank(cc.getPoint());
        BigInteger needPay;

        memberCardRankTextField.setText(rank);
        memberUsagePointTextField.setText(usagePoint.toString());
        memberUsedPointTextField.setText(usedPoint.toString());
        switch (rank) {
            case "Đồng":
            needPay = BigInteger.valueOf(10000000).subtract(pay);
            morePayToNextRank.setText(needPay.toString());
            setVisibleNeedPoint(true);
            break;
            case "Bạc":
            needPay = BigInteger.valueOf(30000000).subtract(pay);
            morePayToNextRank.setText(needPay.toString());
            setVisibleNeedPoint(true);
            break;
            case "Vàng":
            needPay = BigInteger.valueOf(70000000).subtract(pay);
            morePayToNextRank.setText(needPay.toString());
            setVisibleNeedPoint(true);
            break;
            case "Kim Cương":
            setVisibleNeedPoint(false);
        }
    }//GEN-LAST:event_customerTableMouseClicked

    private void CreateNewCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewCardButtonActionPerformed
        // TODO add your handling code here:
        if (checkInformation(
            newMemberFirstNameTextField.getText(),
            newMemberLastNameTextField.getText(),
            newMemberAgeTextField.getText(),
            newMemberPhoneNumberTextField.getText(),
            newMemberAddressTextPane.getText())) {
        if (existedPhoneNumber(newMemberPhoneNumberTextField.getText())) {
            JOptionPane.showMessageDialog(CustomerCardPanel.this,
                "Số điện thoại đã được đăng kí!");
            return;
        }
        JOptionPane.showMessageDialog(CustomerCardPanel.this,
            "Đăng kí thành công!");
        createNewMemberCard();
        resetNewCardValue();
        addAllCustomerCardToTable();
        }
    }//GEN-LAST:event_CreateNewCardButtonActionPerformed
    private void resetNewCardValue() {
        newMemberAddressTextPane.setText("");
        newMemberAgeTextField.setText("");
        newMemberFirstNameTextField.setText("");
        newMemberLastNameTextField.setText("");
        newMemberPhoneNumberTextField.setText("");
    }

    private boolean checkValidString(String firstNameStr, String lastNameStr, String addressStr) {
        if (firstNameStr.isBlank() || lastNameStr.isBlank() || addressStr.isBlank()) {
            return false;
        }
        return true;
    }

    private boolean checkValidNumber(String ageStr, String phoneNumberStr) {
        if (ageStr.isBlank() || phoneNumberStr.isBlank()) {
            return false;
        } else if (cautions.checkIfANumberSequenceForGUI(ageStr) && cautions.checkIfANumberSequenceForGUI(phoneNumberStr)) {
            return true;
        }
        return false;
    }

    private void createNewMemberCard() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardTest().setVisible(true);
            }
        });
    }
    
    private void addAllDataToTable() {
        for (int i = 0; i < cardList.getList().size(); i++) {
            addCustomterToTable(cardList.getList().get(i));
        }
    }
    
    private void addCustomterToTable(CustomerCard customerCard) {
        customerModel.addRow(new Object[]{
                customerCard.getID(),
                customerCard.getCustomer().getFirstName(),
                customerCard.getCustomer().getLastName(),
                customerCard.getCustomer().getAge(),
                customerCard.getCustomer().getGender(),
                customerCard.getCustomer().getGender(),
                customerCard.getCustomer().getPhoneNumber(),
                customerCard.getCustomer().getAddress()
            });
    }

    public void passData(CustomerCardList cardList, IDGenerator idGenerator, History history) {
        this.cardList = cardList;
        this.idGenerator = idGenerator;
        this.history = history;
    }
    private CustomerCardList cardList;
    private IDGenerator idGenerator;
    private History history;
    private Cautions cautions = new Cautions();
    private DefaultTableModel customerModel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddMemberPanel;
    private javax.swing.JPanel CardInforPanel;
    private javax.swing.JButton CreateNewCardButton;
    private javax.swing.JPanel CustomerCardTable;
    private javax.swing.JPanel CustomerInforPanel;
    private javax.swing.JButton DeleteCardButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton ShowCardListButton;
    private javax.swing.JPanel ToolsPanel;
    private javax.swing.JButton UpdateCustomerDateButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane memberAddressTextPane;
    private javax.swing.JTextField memberAgeTextField;
    private javax.swing.JTextField memberCardIDTextField;
    private javax.swing.JTextField memberCardRankTextField;
    private javax.swing.JTextField memberFirstNameTextField;
    private javax.swing.JComboBox<String> memberGenderComboBox;
    private javax.swing.JTextField memberLastNameTextField;
    private javax.swing.JTextField memberPhoneNumberTextField;
    private javax.swing.JTextField memberTotalPayTextField;
    private javax.swing.JTextField memberUsagePointTextField;
    private javax.swing.JTextField memberUsedPointTextField;
    private javax.swing.JLabel morePayToNextRank;
    private javax.swing.JLabel needMore;
    private javax.swing.JTextPane newMemberAddressTextPane;
    private javax.swing.JTextField newMemberAgeTextField;
    private javax.swing.JTextField newMemberFirstNameTextField;
    private javax.swing.JComboBox<String> newMemberGenderComboBox;
    private javax.swing.JTextField newMemberLastNameTextField;
    private javax.swing.JTextField newMemberPhoneNumberTextField;
    private javax.swing.JLabel toNextRank;
    // End of variables declaration//GEN-END:variables
}
