/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.Store;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author FPTSHOP
 */
public final class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     *
     * @param store
     */
    public Header(Store store) {
        initComponents();
        this.store = store;
        setStoreInfor();
        // Kiểm tra nếu có tệp avatar.png trong thư mục gốc của dự án, thì tải hình ảnh lên
        File avatarFile = new File("data/avatar.png");
        if (avatarFile.exists()) {
            try {
                BufferedImage avatarImage = ImageIO.read(avatarFile);
                setChangeLabelImage(avatarImage);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }

    public void setStoreInfor() {
        this.storeNameLabel.setText(store.getName());
        this.storePhoneNumLabel.setText("Liên hệ: " + store.getPhoneNumber());
        this.storeAndressLabel.setText("Địa chỉ: " + store.getAddress());
        this.storeEmailLabel.setText("Email: " + store.getEmail());

    }

    public void setTitle() {
        this.storeNameLabel.setText(store.getName());
        this.storePhoneNumLabel.setText("Liên hệ: " + store.getPhoneNumber());
        this.storeAndressLabel.setText("Địa chỉ: " + store.getAddress());
        this.storeEmailLabel.setText("Email: " + store.getEmail());

    }

    public void setStore(Store store) {
        this.store = store;
    }

    public void setChangeLabelImage(BufferedImage image) {
        if (image != null) {
            // Lưu trữ hình ảnh gốc vào biến scaledImage
            this.scaledImage = image;
            // Vẽ lại panel khi hình ảnh thay đổi
            repaint();

            // Lưu hình ảnh vào tệp (ví dụ: avatar.png trong thư mục gốc của dự án)
            try {
                File outputfile = new File("data/avatar.png");
                ImageIO.write(image, "png", outputfile);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public BufferedImage scaledImage;

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (scaledImage != null) {
            int width = getWidth();
            int height = getHeight();
            int imageSize = Math.min(width, height);

            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Tạo vùng cắt hình tròn
            Ellipse2D.Double circle = new Ellipse2D.Double(60, 10, 100, 100);
            g2d.clip(circle);

            // Vẽ scaledImage trong vùng cắt hình tròn
            g2d.drawImage(scaledImage, 60, 10, 100, 100, null);
            g2d.dispose();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeNameLabel = new javax.swing.JLabel();
        storePhoneNumLabel = new javax.swing.JLabel();
        storeAndressLabel = new javax.swing.JLabel();
        storeEmailLabel = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();

        storeNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        storeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storeNameLabel.setText(" ");

        storePhoneNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        storePhoneNumLabel.setText(" ");

        storeAndressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        storeAndressLabel.setText(" ");

        storeEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        storeEmailLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storeEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(storeAndressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(storePhoneNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(storeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(storeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storePhoneNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(storeAndressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Store store;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel storeAndressLabel;
    private javax.swing.JLabel storeEmailLabel;
    private javax.swing.JLabel storeNameLabel;
    private javax.swing.JLabel storePhoneNumLabel;
    // End of variables declaration//GEN-END:variables
}
