/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.Store;
import java.io.File;

/**
 *
 * @author FPTSHOP
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     *
     * @param store
     */
    public Header(Store store) {
        initComponents();
        setStoreInfor(store);
    }

    private void setStoreInfor(Store store) {
        this.storeNameTextField.setText(store.getName());
        this.storePhoneNumTextField.setText("Liên hệ: " + store.getPhoneNumber());
        this.storeAndressTextField.setText("Địa chỉ: " + store.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new swing.ImageAvatar();
        storeNameTextField = new javax.swing.JLabel();
        storePhoneNumTextField = new javax.swing.JLabel();
        storeAndressTextField = new javax.swing.JLabel();

        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/ImageIcon/avtdis.png"))); // NOI18N

        storeNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        storeNameTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storeNameTextField.setText(" ");

        storePhoneNumTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storePhoneNumTextField.setText(" ");

        storeAndressTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storeAndressTextField.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(storePhoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storeAndressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(storeNameTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storePhoneNumTextField)
                .addGap(3, 3, 3)
                .addComponent(storeAndressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private static final String HOME = System.getProperty("user.dir");
    private static final String SEPARATOR = File.separator;
    private static final String IMAGE_FOLDER = HOME + SEPARATOR + "src" + SEPARATOR + "main" + SEPARATOR + "java" + SEPARATOR + "ImageIcon";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel storeAndressTextField;
    private javax.swing.JLabel storeNameTextField;
    private javax.swing.JLabel storePhoneNumTextField;
    // End of variables declaration//GEN-END:variables
}
