/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controllers.EmployeeListController;
import Controllers.OrderController;
import Controllers.ShiftController;
import Models.Employee;
import Models.EmployeeList;
import Models.Goods;
import Models.History;
import Models.Order;
import Models.Shift;
import Models.Shipment;
import Models.Store;
import Ultility.Cautions;
import Ultility.IDGenerator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPTSHOP
 */
public class ShiftPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShiftJPanel
     */
    public ShiftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shiftDetailPanel = new javax.swing.JPanel();
        ordersAndShipsHistoryPanel = new javax.swing.JPanel();
        flowBtnPanel = new javax.swing.JPanel();
        orderHistoryBtn = new javax.swing.JButton();
        shipmentHistoryBtn = new javax.swing.JButton();
        currentShiftBtn = new javax.swing.JButton();
        searchAndTablePanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        orderIDLabel = new javax.swing.JLabel();
        orderIDTextField = new javax.swing.JTextField();
        cashierPhoneNumLable = new javax.swing.JLabel();
        cashierPhoneNumTextField = new javax.swing.JTextField();
        fromLabel = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        refreashBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        overViewTableJScrollPane = new javax.swing.JScrollPane();
        overViewTable = new javax.swing.JTable();
        otherFunctionPanel = new javax.swing.JPanel();
        currentShiftOverViewPanel = new javax.swing.JPanel();
        openBalanceLabel = new javax.swing.JLabel();
        openBalanceTextField = new javax.swing.JTextField();
        surchargeLabel = new javax.swing.JLabel();
        shiftEmployeeListLabel = new javax.swing.JLabel();
        surchargeTextField = new javax.swing.JTextField();
        shiftEmployeeListComboBox = new javax.swing.JComboBox<>();
        cashierShiftLabel = new javax.swing.JLabel();
        cashierShiftComboBox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        grossRevenueLabel = new javax.swing.JLabel();
        netRevenueLabel = new javax.swing.JLabel();
        taxShiftLabel = new javax.swing.JLabel();
        taxTextField = new javax.swing.JTextField();
        numberOfOrderLabel = new javax.swing.JLabel();
        numberOfOrderTextField = new javax.swing.JTextField();
        netRevenueTextField = new javax.swing.JTextField();
        grossRevenueTextField = new javax.swing.JTextField();
        endShiftBtn = new javax.swing.JButton();
        openShiftBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteArea = new javax.swing.JTextArea();
        displayDetailJScrollPane = new javax.swing.JScrollPane();
        displayDetailTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(977, 645));
        setPreferredSize(new java.awt.Dimension(977, 645));
        setLayout(new java.awt.BorderLayout());

        shiftDetailPanel.setLayout(new java.awt.BorderLayout(10, 0));

        ordersAndShipsHistoryPanel.setPreferredSize(new java.awt.Dimension(350, 595));
        ordersAndShipsHistoryPanel.setLayout(new java.awt.BorderLayout(10, 0));

        flowBtnPanel.setPreferredSize(new java.awt.Dimension(350, 34));

        orderHistoryBtn.setText("Lịch sử HĐ");
        orderHistoryBtn.setMaximumSize(new java.awt.Dimension(200, 23));
        orderHistoryBtn.setMinimumSize(new java.awt.Dimension(50, 23));
        orderHistoryBtn.setPreferredSize(new java.awt.Dimension(110, 23));
        orderHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryBtnActionPerformed(evt);
            }
        });
        flowBtnPanel.add(orderHistoryBtn);

        shipmentHistoryBtn.setText("Lịch sử nhập");
        shipmentHistoryBtn.setMaximumSize(new java.awt.Dimension(200, 200));
        shipmentHistoryBtn.setMinimumSize(new java.awt.Dimension(110, 23));
        shipmentHistoryBtn.setPreferredSize(new java.awt.Dimension(110, 23));
        flowBtnPanel.add(shipmentHistoryBtn);

        currentShiftBtn.setText("Ca hiện tại");
        currentShiftBtn.setOpaque(true);
        currentShiftBtn.setPreferredSize(new java.awt.Dimension(110, 23));
        flowBtnPanel.add(currentShiftBtn);

        ordersAndShipsHistoryPanel.add(flowBtnPanel, java.awt.BorderLayout.PAGE_START);

        searchAndTablePanel.setPreferredSize(new java.awt.Dimension(350, 562));
        searchAndTablePanel.setLayout(new java.awt.BorderLayout(0, 10));

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        searchPanel.setPreferredSize(new java.awt.Dimension(350, 200));

        orderIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderIDLabel.setText("Mã HD: ");

        orderIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cashierPhoneNumLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashierPhoneNumLable.setText("SĐT Thu Ngân:");

        cashierPhoneNumTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashierPhoneNumTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromLabel.setText("Từ :");

        fromTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        toTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        toLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toLabel.setText("Đến :");

        refreashBtn.setBackground(new java.awt.Color(255, 0, 0));
        refreashBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreashBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreashBtn.setText("Làm Mới");
        refreashBtn.setMaximumSize(new java.awt.Dimension(107, 27));
        refreashBtn.setPreferredSize(new java.awt.Dimension(107, 27));
        refreashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreashBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 255, 0));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setText("Tìm Kiếm");
        searchBtn.setMaximumSize(new java.awt.Dimension(107, 27));
        searchBtn.setPreferredSize(new java.awt.Dimension(107, 27));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashierPhoneNumLable)
                            .addComponent(orderIDLabel))
                        .addGap(29, 29, 29)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashierPhoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(fromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreashBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderIDLabel))
                .addGap(15, 15, 15)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashierPhoneNumLable)
                    .addComponent(cashierPhoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toLabel))
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fromLabel)))
                .addGap(30, 30, 30)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        searchAndTablePanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        overViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Thời Gian Lập", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        overViewTable.setFocusable(false);
        overViewTable.setPreferredSize(new java.awt.Dimension(350, 80));
        overViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overViewTableMouseClicked(evt);
            }
        });
        overViewTableJScrollPane.setViewportView(overViewTable);

        searchAndTablePanel.add(overViewTableJScrollPane, java.awt.BorderLayout.CENTER);

        ordersAndShipsHistoryPanel.add(searchAndTablePanel, java.awt.BorderLayout.CENTER);

        shiftDetailPanel.add(ordersAndShipsHistoryPanel, java.awt.BorderLayout.LINE_START);

        otherFunctionPanel.setLayout(new java.awt.BorderLayout(0, 10));

        currentShiftOverViewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng quan ca làm việc"));
        currentShiftOverViewPanel.setPreferredSize(new java.awt.Dimension(617, 234));

        openBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        openBalanceLabel.setText("Nhập Số Dư Đầu Ca : ");

        openBalanceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        openBalanceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        surchargeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surchargeLabel.setText("Chi Tiêu Trong Ca : ");

        shiftEmployeeListLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shiftEmployeeListLabel.setText("Nhân Viên Trực Ca:");

        surchargeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surchargeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        shiftEmployeeListComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shiftEmployeeListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn nhân viên" }));
        shiftEmployeeListComboBox.setSelectedIndex(-1);
        shiftEmployeeListComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shiftEmployeeListComboBoxItemStateChanged(evt);
            }
        });

        cashierShiftLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashierShiftLabel.setText("Thu Ngân Ca:");

        cashierShiftComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashierShiftComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cashierShiftComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cashierShiftComboBoxItemStateChanged(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        grossRevenueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grossRevenueLabel.setText("Doanh Thu Hiện Tại: ");

        netRevenueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        netRevenueLabel.setText("Lợi Nhuận Ròng:");

        taxShiftLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taxShiftLabel.setText("Thuế(VAT-%):");

        taxTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taxTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numberOfOrderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberOfOrderLabel.setText("Tổng Số Hóa Đơn:");

        numberOfOrderTextField.setEditable(false);
        numberOfOrderTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberOfOrderTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        netRevenueTextField.setEditable(false);
        netRevenueTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        netRevenueTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        grossRevenueTextField.setEditable(false);
        grossRevenueTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grossRevenueTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grossRevenueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossRevenueTextFieldActionPerformed(evt);
            }
        });

        endShiftBtn.setBackground(new java.awt.Color(255, 0, 0));
        endShiftBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        endShiftBtn.setForeground(new java.awt.Color(255, 255, 255));
        endShiftBtn.setText("Chốt Ca");
        endShiftBtn.setPreferredSize(new java.awt.Dimension(107, 27));
        endShiftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endShiftBtnActionPerformed(evt);
            }
        });

        openShiftBtn.setBackground(new java.awt.Color(0, 255, 0));
        openShiftBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openShiftBtn.setText("Mở Ca");
        openShiftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openShiftBtnActionPerformed(evt);
            }
        });

        noteArea.setColumns(20);
        noteArea.setRows(5);
        noteArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Ghi chú ca"));
        jScrollPane2.setViewportView(noteArea);

        javax.swing.GroupLayout currentShiftOverViewPanelLayout = new javax.swing.GroupLayout(currentShiftOverViewPanel);
        currentShiftOverViewPanel.setLayout(currentShiftOverViewPanelLayout);
        currentShiftOverViewPanelLayout.setHorizontalGroup(
            currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(openShiftBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxShiftLabel)
                            .addComponent(openBalanceLabel)
                            .addComponent(shiftEmployeeListLabel)
                            .addComponent(cashierShiftLabel)
                            .addComponent(surchargeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(shiftEmployeeListComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 146, Short.MAX_VALUE)
                        .addComponent(cashierShiftComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(openBalanceTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(surchargeTextField))
                    .addComponent(endShiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(numberOfOrderLabel)
                        .addGap(23, 23, 23)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(netRevenueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(grossRevenueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(numberOfOrderTextField)))
                    .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(netRevenueLabel)
                            .addComponent(grossRevenueLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        currentShiftOverViewPanelLayout.setVerticalGroup(
            currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfOrderLabel))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grossRevenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grossRevenueLabel))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netRevenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netRevenueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(currentShiftOverViewPanelLayout.createSequentialGroup()
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openBalanceLabel))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxShiftLabel))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shiftEmployeeListLabel)
                            .addComponent(shiftEmployeeListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashierShiftLabel)
                            .addComponent(cashierShiftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surchargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surchargeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(currentShiftOverViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openShiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endShiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        otherFunctionPanel.add(currentShiftOverViewPanel, java.awt.BorderLayout.PAGE_START);

        displayDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "ĐV", "Đơn Giá/ĐV", "Tổng SL", "Mã Lô", "SL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayDetailJScrollPane.setViewportView(displayDetailTable);

        otherFunctionPanel.add(displayDetailJScrollPane, java.awt.BorderLayout.CENTER);

        shiftDetailPanel.add(otherFunctionPanel, java.awt.BorderLayout.CENTER);

        add(shiftDetailPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void orderHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderHistoryBtnActionPerformed

    private void grossRevenueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossRevenueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossRevenueTextFieldActionPerformed

    private void overViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overViewTableMouseClicked
        int selectedRow = overViewTable.getSelectedRow();
        if (selectedRow != -1) {
            String orderID = overViewTable.getValueAt(selectedRow, 0).toString();
            Order selectedOrder = shiftCtr.containOrder(shift.getOrderHisPerShift(), orderID);
            insertorderGoodsListToDisplayDetailTable(selectedOrder);
        }
    }//GEN-LAST:event_overViewTableMouseClicked

    private void openShiftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openShiftBtnActionPerformed
        if (openBalanceTextField.getText().isBlank()) {
            insertWarningToTextField(openBalanceTextField, EMPTY_TEXT_FIELD_WARNING, 14);
            return;
        }
        if (ctions.checkIfAValidNumberForGUI(openBalanceTextField.getText())) {
            insertWarningToTextField(openBalanceTextField, INVALID_WARNING, 14);
            return;
        }
        if (taxTextField.getText().isBlank()) {
            insertWarningToTextField(taxTextField, EMPTY_TEXT_FIELD_WARNING, 14);
            return;
        }
        if (ctions.checkIfAValidNumberForGUI(taxTextField.getText())) {
            insertWarningToTextField(taxTextField, INVALID_WARNING, 14);
            return;
        }
    }//GEN-LAST:event_openShiftBtnActionPerformed

    private void endShiftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endShiftBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endShiftBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreashBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreashBtnActionPerformed

    private void shiftEmployeeListComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shiftEmployeeListComboBoxItemStateChanged
        if (shiftEmployeeListComboBox.getSelectedIndex() == 0) {// thực hiện thêm nhân viên c

            String inputStr = JOptionPane.showInputDialog(shiftDetailPanel, "Vui lòng thêm nhân viên vào ca:",
                    "Thêm nhân viên", JOptionPane.QUESTION_MESSAGE);
            Employee e = employeeListCtr.containEmployee(employeeList, inputStr,
                    employeeListCtr.BY_PHONE_NUMBER);
            if (e == null) {// kiểm tra xem nhân viên tồn tại hay không 
                JOptionPane.showMessageDialog(shiftDetailPanel, INVALID_WARNING,
                        "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            shift.getEmployeeOfThisShift().getList().add(e);
            shiftEmployeeListComboBox.addItem(e.toString());
        }
    }//GEN-LAST:event_shiftEmployeeListComboBoxItemStateChanged

    private void cashierShiftComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cashierShiftComboBoxItemStateChanged
        int selectedItem = shiftEmployeeListComboBox.getSelectedIndex();
        if (selectedItem == 0) {
            JOptionPane.showMessageDialog(shiftDetailPanel, INVALID_CASHIER_WARNING,
                    "Lỗi", JOptionPane.WARNING_MESSAGE);
        } else {
            shift.setCashier(employeeList.getList().get(selectedItem - 1));
        }
    }//GEN-LAST:event_cashierShiftComboBoxItemStateChanged

    private void passValueToEmployeeListComboBox() {
        employeeList.getList().stream().forEach(
                e -> cashierShiftComboBox.insertItemAt(e.toString(),
                        cashierShiftComboBox.getItemCount()));
    }

    private void setDefaultOptionToTextField(JTextField textField, int size) {
        textField.setFont(new java.awt.Font("Segoe UI", 0, size));
        textField.setForeground(new java.awt.Color(0, 0, 0));
        textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField.setText("");
    }

    private void insertWarningToTextField(JTextField textField, String warningText, int size) {
        textField.setFont(new java.awt.Font("Segoe UI", 2, size)); // NOI18N
        textField.setForeground(new java.awt.Color(255, 0, 0));
        textField.setText(warningText);
        textField.setEditable(false);
    }

    private void insertorderGoodsListToDisplayDetailTable(Order order) {
        clearTableModel(overViewModel);
        for (Goods goods : order.getList()) {
            int size = goods.getShipments().size();
            for (int i = 0; i < size; i++) {
                Shipment shipment = goods.getShipments().get(i);
                if (i == 0) {
                    insertNewOrderGoodsToDisplayDetailTable(goods, shipment);
                } else {
                    insertExistedOrderGoodsToDisplayDetailTable(shipment);
                }
            }
        }
    }

    private void insertNewOrderGoodsToDisplayDetailTable(Goods goods, Shipment shipment) {
        displayDetailModel.addRow(new Object[]{
            goods.getID(),
            goods.getGoodsName(),
            goods.getUnit(),
            goods.getListPrice(),
            goods.getTotalQuantity(),
            shipment.getID(),
            shipment.getQuantity()
        });
    }

    private void insertExistedOrderGoodsToDisplayDetailTable(Shipment shipment) {
        displayDetailModel.addRow(new Object[]{
            "",
            "",
            "",
            "",
            "",
            shipment.getID(),
            shipment.getQuantity()
        });
    }

    private void insertOrderHistoryToOverViewTable(List<Order> orderHistory, Store store) {
        clearTableModel(overViewModel);
        for (Order order : orderHistory) {
            insertNewOrderToOverViewTable(order, store);
        }
    }

    private void insertNewOrderToOverViewTable(Order order, Store store) {
        overViewModel.addRow(new Object[]{
            order.getID(),
            order.getOrderDateTime(),
            orderCtr.getTotal(order, store)
        });
    }

    private void clearTableModel(DefaultTableModel tableModel) {
        int numberOfRow = tableModel.getRowCount();
        for (int i = 0; i < numberOfRow; i++) {
            tableModel.removeRow(0);
        }
    }

    private void setEnableComponentsInSearchPanel(boolean enable) {
        orderIDLabel.setEnabled(enable);
        orderIDTextField.setEnabled(enable);
        cashierPhoneNumLable.setEnabled(enable);
        cashierPhoneNumTextField.setEnabled(enable);
        fromLabel.setEnabled(enable);
        fromTextField.setEnabled(enable);
        toLabel.setEnabled(enable);
        toTextField.setEnabled(enable);
        searchBtn.setEnabled(enable);
        refreashBtn.setEnabled(enable);
    }

    private void setEnableComponentsInCurrentShiftOverViewPanel(boolean enable) {
        surchargeLabel.setEnabled(enable);
        surchargeTextField.setEnabled(enable);
        numberOfOrderLabel.setEnabled(enable);
        numberOfOrderTextField.setEnabled(enable);
        grossRevenueLabel.setEnabled(enable);
        grossRevenueTextField.setEnabled(enable);
        netRevenueLabel.setEnabled(enable);
        netRevenueTextField.setEnabled(enable);
        endShiftBtn.setEnabled(enable);
    }

    private void setEnableComponentsInFlowBtnPanel(boolean enable) {
        orderHistoryBtn.setEnabled(enable);
        shipmentHistoryBtn.setEnabled(enable);
        currentShiftBtn.setEnabled(enable);
    }

    private void setEnableAllComponents(boolean enable) {
        setEnableComponentsInCurrentShiftOverViewPanel(enable);
        setEnableComponentsInSearchPanel(enable);
        setEnableComponentsInFlowBtnPanel(enable);
        overViewTable.setEnabled(enable);
        displayDetailTable.setEnabled(enable);
    }

    private void initVariables() {
        // Table
        overViewModel = (DefaultTableModel) overViewTable.getModel();
        overViewTableJScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        overViewTableJScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        displayDetailModel = (DefaultTableModel) displayDetailTable.getModel();
        displayDetailJScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        displayDetailJScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        // combo box
        passValueToEmployeeListComboBox();
        // open shift frame
        openShiftFrame = new OpenShiftFrame();
        openShiftFrame.passData(employeeList, shift, idgenerator);
        // Biến khác
        orderCtr = new OrderController();
        shiftCtr = new ShiftController();
        employeeListCtr = new EmployeeListController();
        ctions = new Cautions();
    }

    private void initNewShift(){
        openShiftFrame.setVisible(true);
        setEnableAllComponents(openShiftCheck);
    }
    
    public void passData(Shift shift, History history, 
            EmployeeList employeeList, Store myStore, 
            IDGenerator idGenerator) {
        this.shift = shift;
        this.history = history;
        this.employeeList = employeeList;
        this.myStore = myStore;
        this.idgenerator = idGenerator;
        //
        initVariables();
        initNewShift();
    }

    private OpenShiftFrame openShiftFrame;
    private boolean openShiftCheck = false;
    private ShiftController shiftCtr;
    private EmployeeListController employeeListCtr;
    private OrderController orderCtr;
    private DefaultTableModel displayDetailModel;
    private DefaultTableModel overViewModel;
    private Shift shift;
    private History history;
    private EmployeeList employeeList;
    private Store myStore;
    private IDGenerator idgenerator;
    private Cautions ctions;
    private final String OUTPUT_DATE_TIME_PATTERN = "dd/MM/yyyy HH:mm:ss";
    private final String EMPTY_TEXT_FIELD_WARNING = "Ô nhập trống!";
    private final String INVALID_CASHIER_WARNING = "Thu ngân không hợp lệ!";
    private final String INVALID_WARNING = "Không hợp lệ!";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashierPhoneNumLable;
    private javax.swing.JTextField cashierPhoneNumTextField;
    private javax.swing.JComboBox<String> cashierShiftComboBox;
    private javax.swing.JLabel cashierShiftLabel;
    private javax.swing.JButton currentShiftBtn;
    private javax.swing.JPanel currentShiftOverViewPanel;
    private javax.swing.JScrollPane displayDetailJScrollPane;
    private javax.swing.JTable displayDetailTable;
    private javax.swing.JButton endShiftBtn;
    private javax.swing.JPanel flowBtnPanel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel grossRevenueLabel;
    private javax.swing.JTextField grossRevenueTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel netRevenueLabel;
    private javax.swing.JTextField netRevenueTextField;
    private javax.swing.JTextArea noteArea;
    private javax.swing.JLabel numberOfOrderLabel;
    private javax.swing.JTextField numberOfOrderTextField;
    private javax.swing.JLabel openBalanceLabel;
    private javax.swing.JTextField openBalanceTextField;
    private javax.swing.JButton openShiftBtn;
    private javax.swing.JButton orderHistoryBtn;
    private javax.swing.JLabel orderIDLabel;
    private javax.swing.JTextField orderIDTextField;
    private javax.swing.JPanel ordersAndShipsHistoryPanel;
    private javax.swing.JPanel otherFunctionPanel;
    private javax.swing.JTable overViewTable;
    private javax.swing.JScrollPane overViewTableJScrollPane;
    private javax.swing.JButton refreashBtn;
    private javax.swing.JPanel searchAndTablePanel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel shiftDetailPanel;
    private javax.swing.JComboBox<String> shiftEmployeeListComboBox;
    private javax.swing.JLabel shiftEmployeeListLabel;
    private javax.swing.JButton shipmentHistoryBtn;
    private javax.swing.JLabel surchargeLabel;
    private javax.swing.JTextField surchargeTextField;
    private javax.swing.JLabel taxShiftLabel;
    private javax.swing.JTextField taxTextField;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
